# AdviceTemplate
A simple R package to draft ICES advice sheets

## Purpose
ICES provides advice on over 260 fish stocks. In 2017, ICES will provide new advice for 170 of these stocks. Providing uniform and quality controled products is paramount to ICES's mission, however, the number of fish stocks (many with slight variations in data and format) and the practical consideration of having a large network of persons responsible throughout the process can make a consistent product difficult. The impetus, here, is to provide a starting point that reduces Secretariat work load, provides a consistent product, requires no additional software (everything remains a word .docx file!), is mostly hidden from view outside the Secretariat, and is flexible enough for the challenges mentioned above.

## Proposal
The current approach for preparing draft advice sheets is to copy year-1 advice to preserve the format and text drafted by the Advice Drafting Group. Once the file is copied, Secretariat staff must go through and change section numbers, clear values from tables, remove figures, and update references. For the 170 stocks in 2017, it is estimated that this will take close to a month. During Assessment Working Groups, ICES scientists add figures and tables (e.g., from Stock Assessment Graphs) and modify text. Throughout the process, draft advice sheets are version controlled using SharePoint and changes are tracked via Microsoft Word. Here, I propose a few methods to reduce workload for drafting new advice sheets. Further, linking ICES advice to centralized databases (e.g., Stock Assessment Graphs, Stocklist Database, and ICES Historic Catch and Rec-12) will ensure that stock names, ecoregions, standard figures, tables, and format are consistent and have a single, traceable, point of origin. Below, I've broken the process into a few stages based on the challenges, current software availability, and time. Right now, I have code that will get us about to level 2-ish.

Notes:

1. With the implementation of more standardized model output with the ICES Transparent Assessment Framework, some of the limitations mentioned below will be mitigated. 
2. Saving text from year-1 saves considerable time, however, awkward vestiges are sometimes transfered from year to year. The approach outlined below **cannot** preserve text from year-1. 

### Stages
1. The [ReporteRs](https://cran.r-project.org/web/packages/ReporteRs/index.html) package can add relevant information from the SLD (via the [icesSLD](https://github.com/ices-tools-prod/icesSLD) package) to a generic advice sheet template to create a draft advice sheet for each stock. Each draft advice sheet will have updated stock names, section numbers, advice heading, and caption labels saved to a output folder with a specific file name (e.g., O:/<book_number>/<STOCK.CODE>.docx).
  * Advantages: Minimal Secretariat time and effort. Comments added to template are retained in drafts. All information added will be directly from the SLD, ensuring consistency. Creates a feedback loop when errors are noted in draft advice sheets the SLD can be updated.
  * Limitations: Draft advice sheets will not have any information from year-1 and the Secretariat will still need to copy over tables. 
  * Completion: 75% (~ 1 day to be complete for all stocks)
  * Outstanding issues: Header right align published date. Stock name heading hanging tab.

2. Building on the above, the [docxtractr](https://cran.r-project.org/web/packages/docxtractr/index.html) package can harvest tables from year-1 advice sheets and the ReporteRs package can format and add standard tables to the proper location in the draft advice sheets. Splitting the stocks into data categories (Category 1-6) and stock type (e.g., crustacean, elasmobranch, or fish) will be necessary to format and add the different standard tables for each unique type.
  * Advantages: Same as above, but with a much more complete draft. The decision can be made to delete or retain the values in each table.
  * Limitations: Some tables might be too complicated to completely format, but can still be added to draft advice sheets. Footnotes (e.g., *) within tables are retained, however, footnote labels will need to be copied from year-1 advice sheets. Non-standard tables will not be formated and transferred from year-1.
  * Completion: 25% (~ 3-4 days in addition to Stage 1 to complete for most stocks)

3. The table "History of Catch and Landings" can be added directly from the ICES Historical Catch database and Rec-12.  
  * Advantages: Complete provenance from data to advice. 
  * Limitations: Sometimes this table is really complex. Worse, the values presented in advice are completely different from what is found in ICES databases. Is this table really necessary?
  * Completion: 15% (~ 4 days to complete for most stocks)

4. Currently, we create draft advice sheets before the Working Group. If we create draft advice sheets after the final assessment is accepted and uploaded to Stock Assessment Graphs, the icesSAG package can be used to add figures and tables directly into the draft advice sheet.
  * Advantages: Nearly a complete draft advice sheet with full provenance to ICES databases (SLD, SAG, and potentially Historical Catch and Rec-12 databases).
  * Limitations: We would be changing how we work.
  * Completion: 0% (~ 2 days, plus additional time to train supporting staff to generate advice sheets)

## Conclusions
With ~ 1 week of dedicated coding we can probably get to Stage 2.


Tables that should not be transferred from year-1:
History of catch and landings/ commercial catch
Summary of the assessment
